test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /Test

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
